(function(){'use strict';
var root=document.querySelector('.wbce-group-form'),form=root&&root.querySelector('form[name="group"]');if(!form)return;
var basic=root.querySelector('.wbce-group-permissions--basic'),advanced=root.querySelector('.wbce-group-permissions--advanced'),mode=form.elements.advanced,toggle=root.querySelector('[data-group-advanced]'),notice=root.querySelector('.wbce-group-notice');
var map={pages:['pages_view','pages_add','pages_add_l0','pages_settings','pages_modify','pages_intro','pages_delete'],media:['media_view','media_upload','media_rename','media_delete','media_create'],modules:['modules_view','modules_install','modules_uninstall'],templates:['templates_view','templates_install','templates_uninstall'],languages:['languages_view','languages_install','languages_uninstall'],settings:['settings_basic','settings_advanced'],users:['users_view','users_add','users_modify','users_delete'],groups:['groups_view','groups_add','groups_modify','groups_delete'],admintools:['admintools_settings']};
function setVisible(isAdvanced){mode.value=isAdvanced?'yes':'no';basic.hidden=isAdvanced;advanced.hidden=!isAdvanced;basic.style.display=isAdvanced?'none':'';advanced.style.display=isAdvanced?'':'none';toggle.textContent=isAdvanced?'Erweiterte Optionen ausblenden':'Erweiterte Optionen anzeigen';toggle.setAttribute('aria-expanded',isAdvanced?'true':'false');}
function toAdvanced(){Object.keys(map).forEach(function(name){var source=form.elements[name];if(!source)return;map[name].forEach(function(target){if(form.elements[target])form.elements[target].checked=source.checked;});});}
function toBasic(){Object.keys(map).forEach(function(name){var source=form.elements[name];if(!source)return;source.checked=map[name].some(function(target){return form.elements[target]&&form.elements[target].checked;});});}
toggle.addEventListener('click',function(){var next=mode.value!=='yes';if(next&&!form.elements.group_id.value)toAdvanced();else if(!next)toBasic();setVisible(next);});
form.addEventListener('submit',function(event){event.preventDefault();var button=form.querySelector('button[type="submit"]'),title;button.disabled=true;root.classList.add('is-saving');notice.hidden=true;fetch(form.dataset.asyncUrl,{method:'POST',body:new FormData(form),credentials:'same-origin',headers:{'X-Requested-With':'XMLHttpRequest'}}).then(function(response){return response.json().then(function(data){if(!response.ok||!data.ok)throw new Error(data.message||'Speichern fehlgeschlagen.');return data;});}).then(function(data){notice.textContent=data.message;notice.className='wbce-group-notice is-success';notice.hidden=false;if(data.groupIdKey){form.elements.group_id.value=data.groupIdKey;}title=document.getElementById('wbce-group-form-title');if(title&&form.dataset.modifyTitle)title.textContent=form.dataset.modifyTitle;}).catch(function(error){notice.textContent=error.message;notice.className='wbce-group-notice is-error';notice.hidden=false;}).finally(function(){button.disabled=false;root.classList.remove('is-saving');});});
setVisible(mode.value==='yes');
}());
